all: test

test:
	./test_random_numbers.sh

clean:	
	@rm  -f rnd_nums.clean.txt rnd_nums.bin rnd_nums.ent.bytes.report.txt  rnd_nums.ent.bites.report.txt  rnd_nums.dieharder.report.txt urandom.ent.bytes.report.txt urandom.ent.bites.report.txt urandom.dieharder.report.txt
